# use ubuntu trusty for newer version of nodejs, used for JS testing
dist: trusty

# faster builds on new travis setup not using sudo
# temporary disable, see https://github.com/travis-ci/travis-ci/issues/6842
#sudo: false
sudo: required
group: edge

language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_TESTS_PHP=1
    - TASK_TESTS_COVERAGE=0
    - TRAVIS_SECOND_USER=travis_two

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
      env: TASK_TESTS_COVERAGE=1
    - php: nightly

  allow_failures:
    - php: nightly

install:
  - |
    if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
      # disable xdebug for performance reasons when code coverage is not needed
      phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi

  # install composer dependencies
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS

before_script:
  # show some versions and env information
  - php --version
  - composer --version

  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi

  # Disable DEPRECATE messages during PHPUnit initialization on PHP 7.2. To fix them, PHPUnit should be updated to 6.*
  # For Yii2 tests, messages will be enabled by tests/bootstrap.php
  - |
    if [[ $TRAVIS_PHP_VERSION == 7.2 || $TRAVIS_PHP_VERSION = nightly ]]; then
      echo 'Disabled DEPRECATED notifications for PHP >= 7.2';
      echo 'error_reporting = E_ALL & ~E_DEPRECATED' >> /tmp/php-config.ini;
      phpenv config-add /tmp/php-config.ini;
    fi


script:
  # PHP tests
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --exclude-group wincache,xcache
    fi

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

notifications:
  slack:
    -
      rooms:
        -
          secure: TBCEIGmsTCt/1w7K1ZHyqB15cNOJf0ufIsf906byzv4akO3gOFIEs3XRPC23BYuJDkYMxYPk3jH1RIl0W5ZlWwu4j3LeGbzbqvRKZVxHzgJjFDEWW0UT4P7/W/mHcySndF1jczx1SC7YBwJKgaO9IZzCxlQ97ei2izenDqYyZBd6jxujK1c5WhI6V2MlhivT65f1QMEZUuyPMmrrNfpDIgOqw4fQl+2QxjG6Sxs7/L/qL/+tnmBebqmkHzh321cSffNJvooWPeFnYKwdIE94kOQVoMO0njzGtGqsDIjyVPlK99gAVi4J7H1i3Dz092hhoEkYfGxbDTz3egsLUX0NFE5cfczxtLQviz9li9i4oQmky+UaAnCBupDmaNa0wyFYFD81A5nBpa7pCqm9EbeuR8eWDs89kpt4nci+ylmNlOItFQUAYmvtOgXbDBlbgZC9tum+9GeWneKYL+AKYuBVqtZE+FN6/BCvdBLZrxtvs4SotAkJHCpxo/EBqgnHgx7BhE1R5b6B7E8aWiyuZDYUt+aQXq2AWKaOp1iU9H1D8hTNnm6VsxDOgIdjR+wq6GvK29+IVbiukYANvqpAHJ8wZXVwDCCw8FNKBm3xl1F7n9S+I94779umwDYgkD0cmjIdfNaDuRniovfm6F6duiev9WNeQBi9P2WYkXKKqg0MgOA=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: sEMtEPA607dkfWVdBqm7DYThpPVg6S6bY5DV5JKDUEChIrQennkhzPaQ7BEXx1kjIaZ3UCE0FCbS/DD5eNiPAO1lcSNAI9czZ+lXnJflxEnOaL31A00Cq6Y7N8SndEWuz+3siELYsBgiasVMmpPJE9KmefuO3i72yKpux3lyRXX+3DAfRckkWkQfGBPilUtrcl+kfYncBE1LJ/s+h9oTkcOa+Iwq02FQ0LmgBIQ5ycvpQpXOxaseoc/B553Axgad/OVHH/bXs4GbPXVRxxz1vq6xVadSOVaeV7vMxC1hIhhiwl+bYVmr7h3txNF2I8Hqn39vECroG6ZFUIkNk5M57/PdcZYE+mLYCsf1avFGDBkglqPE9m16cLhDdPf4zr6CdBuuO6MK1EXVTYqDNkrlLs4bSz2uxZJXFa8wc6wbKD45LU9ULQ2UfgUDfvmnh7bQv7TDosT0sEkLkQNqp/qkt/Vr3d28zbQUTDD1EirPuxxmVIvfY/AGAKVlF5qgUjD4ZBYsu/MNupDfyOoEj9sgpha92U2DaujdEhtzPDx+v4E8QwspduKJ0KYNj60rM4UA1Epfc3oFJ21vmdqIAd7pKxkE8FpE9fGRd3eRK3F4rMqvgf2laOej4TjgOIxG79rZpKOnvORkM6266D7gXFNTcmrt2AaXJPBfZleLTZ6JJNw=
      on_success: never
      on_failure: always
      on_pull_requests: false
